version: '3'

services:
  kafka:
    image: chengkuan/kafka-2.13-2.8.0:latest
    ports:
     - 9092:9092
     - 9093:9093
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
  CheckInCamel:
    image: chengkuan/checkincamel:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_BUILD:-jvm}
    links:
     - kafka
    environment:
     - QUARKUS_ARTEMIS_URL=tcp:/amq:61616
     - QUARKUS_ARTEMIS_USERNAME=admin
     - QUARKUS_ARTEMIS_PASSWORD=admin
     - KAFKA_SERVER=kafka:9092
     #- QUARKUS_LOG_LEVEL=DEBUG
     - QUARKUS_LOG_CATEGORY_\"blog.braindose\"_LEVEL=DEBUG
    depends_on:
      kafka:
        condition: service_healthy
  amq:
    image: chengkuan/apache-artemis:2.17.0-SNAPSHOT
    environment:
     - ARTEMIS_USER=admin
     - ARTEMIS_PASSWORD=admin
    ports:
     - 61616:61616
     - 8161:8161
    volumes:
      - /var/lib/artemis-instance
    depends_on:
      kafka:
        condition: service_healthy